In [25]:
import numpy as np
from   numpy.polynomial.legendre import legval
from   scipy.special             import eval_legendre

In [34]:
Ar = np.genfromtxt("Data/HCNAr_chinois.csv", delimiter=";", names=True, dtype=None, encoding="utf-8")

# Suppression des 8 dernières lignes
Ar = Ar[-83:-8]

In [10]:
Theta = [0,10,20,30,40,50,60]
b = [1,2,3,4,5,6]
cosTh = np.cos(np.deg2rad(np.asarray(Theta, dtype=float)))
Theta, b, cosTh

([0, 10, 20, 30, 40, 50, 60],
 [1, 2, 3, 4, 5, 6],
 array([1.        , 0.98480775, 0.93969262, 0.8660254 , 0.76604444,
        0.64278761, 0.5       ]))

In [67]:
B=legval(cosTh,b)
B

array([21.        , 18.44618753, 12.01636332,  4.68364337, -0.54125005,
       -2.22061865, -1.03125   ])

In [55]:
R=5
i = np.arange(6)
g0 = np.asarray([1,2,3,4,5,6], dtype=float)
g1 = np.asarray([7,8,9,1,2,3], dtype=float)
g2 = np.asarray([4,5,6,7,8,9], dtype=float)
g3 = np.asarray([1,2,3,4,5,6], dtype=float)
g = g0[i, None] + R * (g1[i, None] + R * (g2[i, None] + R *  g3[i, None]))
g

array([[261.],
       [417.],
       [573.],
       [684.],
       [840.],
       [996.]])

In [54]:
Pl = np.asarray([eval_legendre(l, cosTh) for l in range(6)])
Pl

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ],
       [ 1.        ,  0.98480775,  0.93969262,  0.8660254 ,  0.76604444,
         0.64278761,  0.5       ],
       [ 1.        ,  0.95476947,  0.82453333,  0.625     ,  0.38023613,
         0.11976387, -0.125     ],
       [ 1.        ,  0.91056878,  0.66488473,  0.32475953, -0.02523333,
        -0.30022052, -0.4375    ],
       [ 1.        ,  0.8532095 ,  0.47497774,  0.0234375 , -0.31900435,
        -0.42753446, -0.2890625 ],
       [ 1.        ,  0.78399017,  0.27149175, -0.22327217, -0.41968205,
        -0.25448851,  0.08984375]])

In [64]:
np.shape(g * Pl)

(6, 7)

In [69]:
np.shape(np.sum(g * Pl, axis=0) * np.exp(B))

(7,)